version: "3"
services:
  api-gateway-svc:
    build:
      context: ../
      dockerfile: integration_tests/Dockerfile
    environment:
      port: 80
      user-service-base-url: "http://user-service"
      message-service-base-url: "http://message-service"
      enable-discovery-client: "True"
      eureka-server-url: "http://service-registry-svc/eureka/v2/"
      logging-level: "TRACE"
    ports:
      - 80:80
    depends_on:
      - service-registry-svc
    networks:
      - app
    command: "python3 integration_tests/app/api_gateway.py"
  service-registry-svc:
    build:
      context: ../
      dockerfile: integration_tests/Dockerfile
    environment:
      port: 80
      logging-level: "TRACE"
    networks:
      - app
    command: "python3 integration_tests/app/service_registry.py"
  user-svc-1: &svc-base
    build:
      context: ../
      dockerfile: integration_tests/Dockerfile
    environment:
      port: 80
      eureka-server-url: "http://service-registry-svc/eureka/v2/"
      logging-level: "TRACE"
    depends_on:
      - service-registry-svc
    networks:
      - app
    command: "python3 integration_tests/app/user_service.py"
  user-svc-2:
    <<: *svc-base
  user-svc-3:
    <<: *svc-base
  message-svc:
    build:
      context: ../
      dockerfile: integration_tests/Dockerfile
    environment:
      port: 80
      eureka-server-url: "http://service-registry-svc/eureka/v2/"
      logging-level: "TRACE"
      # message-svc should directly invoke the user-svc via the service discovery
      user-service-host: user-service
    depends_on:
      - service-registry-svc
    networks:
      - app
    command: "python3 integration_tests/app/message_service.py"

networks:
  app:
